[package]
name = "sp1-sharpe-script"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-sdk = "4.1.7"
sp1-build = "4.1.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }

[build-dependencies]
sp1-build = "4.1.7"
